version: '3'

services:
  database:
    image: postgres
    restart: 'no'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kptzmi321
      POSTGRES_DB: priorityhub